name: Run Backend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kod
        uses: actions/checkout@v3

      - name: Installera Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installera beroenden
        run: npm install

      - name: Kör tester
        run: npm test
