name: Run Backend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: swingnotes_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/swingnotes_test_db
      NODE_ENV: test

    steps:
      - name: Checkout kod
        uses: actions/checkout@v3

      - name: Installera Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installera beroenden
        run: npm install

      - name: Vänta på att databasen blir tillgänglig
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "PostgreSQL är redo" && exit 0
            echo "Väntar på PostgreSQL..."
            sleep 3
          done
          echo "Kunde inte ansluta till PostgreSQL" && exit 1

      - name: Kör tester
        run: npm test
